apiVersion: v1
entries:
  as:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-05-27T13:53:36.510192Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 6467a52225790609f251bb218d72a13986c5db336ff18715f45945e4df0a52eb
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: as
    urls:
    - as-0.1.0.tgz
    version: 0.1.0
generated: "2020-05-27T13:53:36.4983272Z"
